import assert from 'node:assert/strict';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';

const modulePath = process.env.PUPPETEER_MODULE;
const { default: puppeteer } = await import(modulePath ? pathToFileURL(modulePath).href : 'puppeteer-core');
const base = process.env.DRIFT_URL || 'http://127.0.0.1:8000';
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_EXECUTABLE || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true,
  args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const artifacts = new URL('./artifacts/', import.meta.url);
fs.mkdirSync(artifacts, { recursive: true });
const errors = [];
const page = await browser.newPage();
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.setViewport({ width: 1440, height: 960, deviceScaleFactor: 1 });
try {
  await page.goto(base, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.driftStats?.frames > 0, { timeout: 15000 });
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('#fractal')).opacity) > 0.99);
  await page.screenshot({ path: new URL('desktop-initial.png', artifacts).pathname });
  await page.click('#start');
  await page.mouse.move(630, 430);
  await page.waitForFunction(() => window.driftStats?.depth > 0.15);
  const running = await page.evaluate(() => window.driftStats);
  assert.equal(running.running, true);
  assert.ok(Math.abs(running.target[0] - 630 / 1440) < 0.001);
  await page.keyboard.press('Space');
  await page.waitForFunction(() => window.driftStats?.running === false);
  const paused = await page.evaluate(() => window.driftStats.depth);
  await new Promise(r => setTimeout(r, 180));
  assert.equal(await page.evaluate(() => window.driftStats.depth), paused);
  const beforePan = await page.evaluate(() => window.driftStats);
  await page.mouse.move(720, 480);
  await page.mouse.down();
  await page.mouse.move(820, 440, { steps: 8 });
  await page.waitForFunction(x => window.driftStats?.dragging && window.driftStats.center[0] < x, {}, beforePan.center[0] - beforePan.scale * 0.05);
  const duringPan = await page.evaluate(() => window.driftStats);
  assert.equal(duringPan.depth, beforePan.depth);
  await page.mouse.up();
  await page.waitForFunction(() => !window.driftStats?.dragging && !window.driftStats?.running);
  const beforeGo = await page.evaluate(() => window.driftStats);
  const click = { x: 860, y: 390 };
  const expectedCenter = [beforeGo.center[0] + beforeGo.scale * (click.x / 1440 * 2 - 1) * beforeGo.width / beforeGo.height,
    beforeGo.center[1] + beforeGo.scale * (1 - click.y / 960 * 2)];
  await page.mouse.click(click.x, click.y);
  await page.waitForFunction(() => window.driftStats?.navigating);
  await page.waitForFunction(() => !window.driftStats?.navigating && window.driftStats?.running);
  const afterGo = await page.evaluate(() => window.driftStats);
  assert.ok(Math.abs(afterGo.center[0] - expectedCenter[0]) < 1e-8);
  assert.ok(Math.abs(afterGo.center[1] - expectedCenter[1]) < 1e-8);
  assert.ok(afterGo.iterations >= 544 && afterGo.iterations <= 4096);
  await page.keyboard.press('Space');
  await page.waitForFunction(() => !window.driftStats?.running);
  const wheelStart = await page.evaluate(() => window.driftStats.depth);
  await page.mouse.move(720, 480);
  await page.mouse.wheel({ deltaY: -120 });
  await page.waitForFunction(d => window.driftStats?.running && window.driftStats.direction === 1 && window.driftStats.depth > d + 0.08, {}, wheelStart);
  await page.mouse.wheel({ deltaY: 120 });
  await page.waitForFunction(() => window.driftStats?.direction === -1 && window.driftStats.velocity < -0.05);
  const reversing = await page.evaluate(() => window.driftStats.depth);
  await page.waitForFunction(d => window.driftStats.depth < d - 0.06, {}, reversing);
  await page.keyboard.press('Space');
  await page.waitForFunction(() => !window.driftStats.running);
  await page.click('#about-button');
  assert.equal(await page.$eval('#about', d => d.open), true);
  assert.match(await page.$eval('#about', d => d.textContent), /Δ/);
  assert.match(await page.$eval('#about', d => d.textContent), /synthesized/);
  await page.screenshot({ path: new URL('desktop-math.png', artifacts).pathname });
  await page.click('#close-about');
  await page.click('#wander');
  await page.waitForFunction(() => window.driftStats?.refreshes > 0 && window.driftStats?.transitioning === false, { timeout: 10000 });
  await page.screenshot({ path: new URL('desktop-detail.png', artifacts).pathname });
  await page.click('[data-palette="1"]');
  assert.equal(await page.$eval('[data-palette="1"]', x => x.getAttribute('aria-pressed')), 'true');
  await page.select('#quality', 'light');
  await page.waitForFunction(() => window.driftStats?.width * window.driftStats?.height < 85000);
  await page.click('#reset');
  await page.waitForFunction(() => window.driftStats?.depth === 0 && !window.driftStats?.running);
  assert.equal(await page.$eval('body', b => b.classList.contains('exploring')), false);
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  await page.waitForFunction(() => window.driftStats?.height > window.driftStats?.width);
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('#fractal')).opacity) > 0.99);
  await page.screenshot({ path: new URL('mobile-initial.png', artifacts).pathname });
  await page.click('#about-button');
  await page.$eval('#about', d => { d.scrollTop = d.scrollHeight; });
  assert.equal(await page.$eval('#about', d => d.scrollWidth > d.clientWidth), false);
  await page.screenshot({ path: new URL('mobile-math.png', artifacts).pathname });
  await page.click('#close-about');
  assert.equal(await page.$eval('#about', d => d.open), false);
  await page.click('#start');
  await page.touchscreen.tap(260, 250);
  await page.waitForFunction(() => window.driftStats?.running && window.driftStats?.navigating);
  await page.waitForFunction(() => window.driftStats?.running && !window.driftStats?.navigating);
  const mobile = await page.evaluate(() => window.driftStats);
  assert.equal(mobile.target[0], 0.5);
  const cdp = await page.createCDPSession();
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 150, y: 450 }] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 200, y: 510 }] });
  await page.waitForFunction(() => window.driftStats?.dragging);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await page.waitForFunction(() => !window.driftStats?.dragging);
  await page.screenshot({ path: new URL('mobile-running.png', artifacts).pathname });
  assert.deepEqual(errors, []);
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  assert.equal(overflow, false);
  await page.goto(`${base}?renderer=scalar`, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.driftStats?.backend === 'scalar');
  // Inspect a deep render without waiting for real-time travel. This separate
  // engine does not alter the production worker or expose a debug control.
  await page.setViewport({ width: 1440, height: 960, deviceScaleFactor: 1, isMobile: false, hasTouch: false });
  await page.goto(`${base}?renderer=scalar`, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => window.driftStats.width > window.driftStats.height);
  const deepDiagnostics = await page.evaluate(async () => {
    const { instance } = await WebAssembly.instantiate(await (await fetch('mandelbrot_drift.wasm')).arrayBuffer());
    const api = instance.exports;
    const engine = api.engine_create(576, 384);
    let pointer;
    const mx = 0.5 + (-0.743643887037151 + 0.5) / (2 * 1.32 * 1.5);
    const my = 0.5 - 0.13182590420533 / (2 * 1.32);
    for (let i = 0; i < 52; i++) pointer = api.engine_step(engine, 0.1, mx, my, 2.5, 1);
    const canvas = document.querySelector('#fractal');
    canvas.width = 576; canvas.height = 384;
    canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(api.memory.buffer, pointer, 576 * 384 * 4).slice(), 576, 384), 0, 0);
    document.body.classList.add('exploring');
    document.querySelector('#depth').textContent = '13.00';
    const diagnostics = { depth: api.engine_stat(engine, 0), iterations: api.engine_stat(engine, 10), detailBlend: api.engine_stat(engine, 15) };
    api.engine_free(engine);
    return diagnostics;
  });
  assert.equal(deepDiagnostics.detailBlend, 0);
  assert.ok(deepDiagnostics.iterations > 3000);
  await page.waitForFunction(() => Number(getComputedStyle(document.querySelector('#intro')).opacity) < 0.01);
  await page.screenshot({ path: new URL('desktop-deep.png', artifacts).pathname });
  fs.writeFileSync(new URL('browser-results.json', artifacts), JSON.stringify({ running, duringPan, afterGo, mobile, deepDiagnostics, errors, scalarFallback: true }, null, 2));
  console.log('Passed: SIMD/scalar WASM, steering, drag/pan, click-to-go, pause, reset, refresh, palettes, detail controls, wheel reversal, math panel, and mobile tap/drag.');
} catch (error) {
  console.error(await page.evaluate(() => ({ stats: window.driftStats, viewport: [innerWidth, innerHeight], status: document.querySelector('#load-status')?.textContent })));
  throw error;
} finally { await browser.close(); }
