"""Generate independent 90-decimal-digit escape-color fixtures (standard library)."""
from decimal import Decimal, localcontext
from pathlib import Path
import math

rows = []
with localcontext() as ctx:
    ctx.prec = 90
    for dx, dy in [(-1, -1), (0, 0), (1, 1), (-1, 1), (1, -1)]:
        cx = Decimal.from_float(-0.743643887037151) + Decimal.from_float(dx * 1e-13)
        cy = Decimal.from_float(0.13182590420533) + Decimal.from_float(dy * 1e-13)
        x = y = Decimal(0)
        mu = -1.0
        for n in range(4096):
            magnitude = x*x + y*y
            if magnitude > 256:
                mu = n + 1 - math.log2(0.5 * math.log2(float(magnitude)))
                break
            x, y = x*x - y*y + cx, 2*x*y + cy
        rows.append(f'    ({float(dx)}, {float(dy)}, {mu!r}),')
Path(__file__).with_name('precision_reference.inc').write_text(
    '// Generated by tests/precision-reference.py using 90-digit Decimal orbits.\n'
    'const DECIMAL_REFERENCE: [(f64,f64,f64);5] = [\n' + '\n'.join(rows) + '\n];\n'
)
